# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: simple-api


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        run: |
          docker build --tag $IMAGE_NAME:${{ github.sha }} .

      # need push to docker image registry

      - name: Remove Image on success
        if: success()
        run: |
          docker rmi $IMAGE_NAME:${{ github.sha }}

      - name: Remove None Image on failure
        if: failure()
        run: |
          docker images -a |  grep "<none>" | awk '{print $3}' | xargs docker rmi
          

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout to infra repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: eunjuukim/simple-k8s


      - name: setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: update Kubernetes resources
        run: |
          cd app/overlays/dev
          kustomize edit set image simple-api=simple-api:${{ github.sha }}
          kustomize build .

      - name: commit changes
        run: |
          git add app/overlays/dev
          git config --global user.email "developer@email.com"
          git config --global user.name "github action"
          git commit -m "update image tag $GITHUB_SHA"
          git push
